# Generated by Django 6.0.3 on 2026-04-01 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(help_text='URL amigable para SEO', unique=True)),
                ('descripcion_seo', models.TextField(blank=True, help_text='Meta descripción para buscadores')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='categorias/')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('slug', models.SlugField(help_text='URL amigable para SEO (ej: tarjeta-rebanadora-bizerba)', unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU / Código Interno')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (MXN)')),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('estado_stock', models.CharField(choices=[('disponible', 'Disponible'), ('bajo_pedido', 'Bajo Pedido'), ('agotado', 'Agotado')], default='disponible', max_length=20)),
                ('disponible', models.BooleanField(default=True, verbose_name='Activo en el sitio')),
                ('meta_titulo', models.CharField(blank=True, help_text='Título SEO (Máx 70 caracteres)', max_length=70)),
                ('meta_descripcion', models.CharField(blank=True, help_text='Meta descripción SEO (Máx 160 caracteres)', max_length=160)),
                ('descripcion_corta', models.TextField(help_text='Extracto para listados', max_length=500)),
                ('descripcion_detallada', models.TextField(help_text='Descripción técnica enriquecida')),
                ('modelos_compatibles', models.JSONField(default=list, help_text="Ej: ['GSP H', 'H33']")),
                ('numeros_parte_oem', models.JSONField(default=list, help_text="Ej: ['603 85 07 51 02']")),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('alt_text', models.CharField(help_text='Texto descriptivo para Google Images (SEO)', max_length=200)),
                ('es_principal', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
            },
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Ej: Voltaje, Material, Protección', max_length=50)),
                ('valor', models.CharField(help_text='Ej: 110V, FR4 Militar, IP65', max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Especificación Técnica',
                'verbose_name_plural': 'Especificaciones Técnicas',
            },
        ),
    ]
