# Generated by Django 6.0.3 on 2026-04-01 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('servicio', models.CharField(choices=[('hardware', 'Desarrollo de Hardware (PCB)'), ('software', 'Software Industrial / Nube'), ('domotica', 'Domótica y Control de Accesos'), ('3d', 'Diseño e Impresión 3D'), ('soporte', 'Mantenimiento o Soporte'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
