# Generated by Django 6.0.3 on 2026-04-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(help_text='Ej: Proyectos Industriales', max_length=100)),
                ('valor', models.CharField(help_text='Ej: +50', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='InfoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_titulo', models.CharField(default='Ingeniería real para problemas reales.', max_length=200)),
                ('hero_descripcion', models.TextField(help_text='Texto principal bajo el título')),
                ('historia_titulo', models.CharField(default='Nuestra misión en la planta', max_length=200)),
                ('historia_cuerpo', models.TextField(help_text='Relato cercano sobre cómo nació Control Modular MX')),
                ('meta_titulo', models.CharField(blank=True, max_length=70)),
                ('meta_descripcion', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Información de la Empresa',
                'verbose_name_plural': 'Información de la Empresa',
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True, help_text='Pequeña descripción humana')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipo/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para decidir quién sale primero')),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Miembros del Equipo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Valor de la Empresa',
                'verbose_name_plural': 'Valores de la Empresa',
                'ordering': ['orden'],
            },
        ),
    ]
