# Generated by Django 6.0.3 on 2026-04-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoempresa',
            name='historia_imagen',
            field=models.ImageField(blank=True, help_text='Imagen lateral de la sección historia', null=True, upload_to='empresa/'),
        ),
    ]
